Description:
    Jubin Mohanty
    Cloudformation for iam_s3bucket_Policy/ Sept 2020

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

Resources:
  S3CodeBucketCopyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /

  RootInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref S3CodeBucketCopyRole

  S3CodeBucketCopyPolicy:
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName: S3CodeBucketCopyPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement: 
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource: "*"
      Roles: 
        - !Ref S3CodeBucketCopyRole

Outputs:
  RootInstance:
    Description: "Will Allow EC2 instances to use web app"
    Value: !Ref RootInstanceProfile
    Export:
      Name: !Sub ${EnvironmentName}-ROOT_INST
